/**
 * Dashboard HTML generator — orchestrates all modules into a single self-contained HTML file.
 *
 * Composes CSS, shared JS, and tab-specific JS into one HTML string with all data inlined.
 * Each tool tab (Fitness, Simulation) has subtabs: Overview, Catalog, Recipes.
 */

import type { StoredSession, CheckCatalogEntry, RecipeCatalogEntry } from '../store.js'

import { dashboardCss } from './css.js'
import { dashboardSharedJs } from './shared.js'
import { dashboardOverviewJs } from './overview.js'
import { dashboardSessionsJs } from './sessions.js'
import { dashboardChecksJs } from './checks.js'
import { dashboardRecipesJs } from './recipes.js'
import { dashboardToolTabsJs } from './tool-tabs.js'

export function generateDashboardHtml(
  sessions: StoredSession[],
  checkCatalog: CheckCatalogEntry[] = [],
  recipeCatalog: RecipeCatalogEntry[] = [],
): string {
  const latest = sessions[0]
  const safeDataJson = JSON.stringify(sessions).replace(/<\//g, '<\\/')
  const safeCatalogJson = JSON.stringify(checkCatalog).replace(/<\//g, '<\\/').replace(/</g, '\\u003c')
  const safeRecipeJson = JSON.stringify(recipeCatalog).replace(/<\//g, '<\\/')

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>OpenSIP Tools</title>
<link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='32' height='32' viewBox='0 0 24 24' fill='none'%3E%3Cpath d='M4 8h12a4 4 0 0 1 0 8h-1M4 8v8a4 4 0 0 0 4 4h4a4 4 0 0 0 4-4V8M4 8H2M6 4c0 1 .5 2 1 2.5M10 3c0 1.5.5 2.5 1 3M14 4c0 1 .5 2 1 2.5' stroke='%23c4956a' stroke-width='1.5' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&display=swap" rel="stylesheet">
<style>
${dashboardCss()}
</style>
</head>
<body>

<div class="header">
  <span class="header-icon"><svg width="28" height="28" viewBox="0 0 24 24" fill="none"><path d="M4 8h12a4 4 0 0 1 0 8h-1M4 8v8a4 4 0 0 0 4 4h4a4 4 0 0 0 4-4V8M4 8H2M6 4c0 1 .5 2 1 2.5M10 3c0 1.5.5 2.5 1 3M14 4c0 1 .5 2 1 2.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg></span>
  <div><h1><span class="brand-open">Open</span>SIP Tools</h1></div>
</div>

<div class="tab-bar" id="tab-bar">
  <div class="tab active" data-tab="overview"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="7" height="9" x="3" y="3" rx="1"/><rect width="7" height="5" x="14" y="3" rx="1"/><rect width="7" height="9" x="14" y="12" rx="1"/><rect width="7" height="5" x="3" y="16" rx="1"/></svg> Overview</div>
  <div class="tab" data-tab="fitness"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.596 12.768a2 2 0 1 0 2.829-2.829l-1.768-1.767a2 2 0 0 0 2.828-2.829l-2.828-2.828a2 2 0 0 0-2.829 2.828l-1.767-1.768a2 2 0 1 0-2.829 2.829z"/><path d="m2.5 21.5 1.4-1.4"/><path d="m20.1 3.9 1.4-1.4"/><path d="M5.343 21.485a2 2 0 1 0 2.829-2.828l1.767 1.768a2 2 0 1 0 2.829-2.829l-6.364-6.364a2 2 0 1 0-2.829 2.829l1.768 1.767a2 2 0 0 0-2.828 2.829z"/><path d="m9.6 14.4 4.8-4.8"/></svg> Fitness</div>
  <div class="tab" data-tab="simulation"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14 2v6a2 2 0 0 0 .245.96l5.51 10.08A2 2 0 0 1 18 22H6a2 2 0 0 1-1.755-2.96l5.51-10.08A2 2 0 0 0 10 8V2"/><path d="M6.453 15h11.094"/><path d="M8.5 2h7"/></svg> Simulation</div>
</div>

<div id="panel-overview" class="tab-panel active"></div>
<div id="panel-fitness" class="tab-panel"></div>
<div id="panel-simulation" class="tab-panel"></div>

<div class="footer">Generated by <strong>opensip-tools</strong> &mdash; <a href="https://opensip.ai">opensip.ai</a></div>

<script>
const sessions = ${safeDataJson};
const checkCatalog = ${safeCatalogJson};
const recipeCatalog = ${safeRecipeJson};
const fitSessions = sessions.filter(s => s.tool === 'fit');
const simSessions = sessions.filter(s => s.tool === 'sim');

${dashboardSharedJs()}
${dashboardOverviewJs()}
${dashboardSessionsJs()}
${dashboardChecksJs()}
${dashboardRecipesJs()}
${dashboardToolTabsJs()}

// =======================================================
// RENDER TABS
// =======================================================
renderOverview();
renderFitnessTab();
renderSimulationTab();
</script>
</body>
</html>`
}
